;;;
;;; Main file for my emacs config
;;;

(load "pkgs")
(load "bell")
(load "indentation")
(load "theme")
(load "killbloat")
(load "wind")
(load "fullscr")
(load "modeln")
(load "cfix")
(load "osxfix")
;(load "winfix")
(load "pth")
(load "cnfirc")
(load "msc")
(load "cnfslime")
(load "twttr")
(load "cmpltn")
(load "cnforg")
(load "cnfboo")
(load "cnfel")
(load "cnflispmode")
(load "cnfcompile")
(load "cnfrkt")
(load "cnfdale")
